
package com.example.companyfind.gus;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: A1FD148DE831CDAA5425905FF4FD05D6C2AAC623EEC2913D71D550BDFE0F823C1D7A95A12C8821A6F7359FB4571406AC6C7E3491B4BDEC94D9B4105B9E24C0B0
//------------------------------------------------------------------------
import java.net.URL;
import java.io.*;
import java.net.HttpURLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.List;

public interface FMDConnectionProvider
{
    FMDResponseData sendRequest(String url,String requestBody,HashMap< String,String> httpHeaders, FMDRequestResultHandler handler,String contentType) throws java.lang.Exception;
}

class FMDHttpConnectionProvider implements FMDConnectionProvider{

    public void prepareRequest(HttpURLConnection url,String requestBody, FMDRequestResultHandler handler,String contentType ) throws java.lang.Exception {
        OutputStreamWriter wr = new OutputStreamWriter(url.getOutputStream());
        wr.write(requestBody);
        wr.flush();
    }

    @Override
    public FMDResponseData sendRequest(String url,String requestBody, HashMap< String, String> httpHeaders,FMDRequestResultHandler handler,String contentType ) throws java.lang.Exception
    {
        URL urlObject=new URL(url);
        HttpURLConnection connection=(HttpURLConnection)urlObject.openConnection();
        connection.setRequestMethod("POST");
        for(Map.Entry<String, String> entry : httpHeaders.entrySet())
        {
            connection.setRequestProperty(entry.getKey(),entry.getValue());
        }
        connection.setRequestProperty("user-agent","https://easyWSDL.com Generator 9.3.3.2");
        prepareRequest(connection,requestBody,handler, contentType );


        FMDResponseData response=new FMDResponseData();
        for(Map.Entry<String, List<String>> entry : connection.getHeaderFields().entrySet())
        {
            if(entry.getKey()!=null)
            {
                String values = "";
                for (String value : entry.getValue()) {
                    values = values + value;
                }
                response.getHeaders().put(entry.getKey(),values);
            }
        }
        
        try(InputStream dataStream = getResponseStream(connection,response,handler))
        {
            response.setBody(FMDHelper.streamToString(dataStream));
        }
        
        return response;
    }

    protected InputStream getResponseStream(
        HttpURLConnection url,
        FMDResponseData response,
        FMDRequestResultHandler handler
    ) throws java.lang.Exception
    {
        try{
            return url.getInputStream();
        }
        catch (IOException ex)
        {
            return url.getErrorStream();
        }
    }
}