
package com.example.companyfind.gus;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: A1FD148DE831CDAA5425905FF4FD05D6C2AAC623EEC2913D71D550BDFE0F823C1D7A95A12C8821A6F7359FB4571406AC6C7E3491B4BDEC94D9B4105B9E24C0B0
//------------------------------------------------------------------------

import java.util.*;


public class FMDe3
{
    private String url = "https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc";
    private final HashMap< String,String> httpHeaders = new HashMap< String,String>();
    private boolean enableLogging = false;
    private String userName=null;
    private String password=null;
    private FMDConnectionProvider connectionProvider=new FMDHttpConnectionProvider();

    public FMDe3()
    {
    }

    public FMDe3(String url)
    {
        this.url=url;
    }

    public FMDe3 (String url,FMDConnectionProvider connectionProvider) {
        this.url=url;
        this.connectionProvider=connectionProvider;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public HashMap<String, String> getHttpHeaders() {
        return httpHeaders;
    }

    public boolean isLoggingEnabled() {
        return enableLogging;
    }

    public void setLoggingEnabled(boolean enableLogging) {
        this.enableLogging = enableLogging;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    

    
    protected FMDRequestResultHandler createRequestResultHandler()
    {
        FMDRequestResultHandler handler = new FMDRequestResultHandler(FMDSoapVersion.v1_2);
        return handler;
    }
    
    private org.w3c.dom.Document createGetValueRequest(final String pNazwaParametru,FMDRequestResultHandler __handler) throws java.lang.Exception
    {
        org.w3c.dom.Document __xml=__handler.createEnvelopeXml();
        ArrayList<String> __referenceParameters = new ArrayList<>();
        __handler.addWSAddressingHeaders("http://CIS/BIR/2014/07/IUslugaBIR/GetValue", "http://www.w3.org/2005/08/addressing/anonymous", this.url, __referenceParameters);
        org.w3c.dom.Element __mainNode=__handler.writeElement("http://CIS/BIR/2014/07","GetValue",__xml);
        __handler.getBody().appendChild(__mainNode);

        org.w3c.dom.Element __pNazwaParametruItemElement=__handler.writeElementWithType(pNazwaParametru,String.class, "pNazwaParametru", "http://CIS/BIR/2014/07", __mainNode, true);
        if(__pNazwaParametruItemElement != null)
        {
            __pNazwaParametruItemElement.setTextContent(pNazwaParametru);
        }
        __handler.finishEnvelopeXml(__xml);
        return __xml;
    }
    
    public String GetValue(final String pNazwaParametru) throws java.lang.Exception
    {
        FMDRequestResultHandler __handler =createRequestResultHandler();
        org.w3c.dom.Document __xml=createGetValueRequest(pNazwaParametru, __handler);
        sendRequest("http://CIS/BIR/2014/07/IUslugaBIR/GetValue",__xml,__handler);
        org.w3c.dom.Node __result=FMDHelper.getResult(__handler.getOutputBody(), "GetValueResult",false);
        if(__result!=null)
        {
            return __result.getTextContent();
        }
        return null;
    }
    private org.w3c.dom.Document createZalogujRequest(final String pKluczUzytkownika,FMDRequestResultHandler __handler) throws java.lang.Exception
    {
        org.w3c.dom.Document __xml=__handler.createEnvelopeXml();
        ArrayList<String> __referenceParameters = new ArrayList<>();
        __handler.addWSAddressingHeaders("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", "http://www.w3.org/2005/08/addressing/anonymous", this.url, __referenceParameters);
        org.w3c.dom.Element __mainNode=__handler.writeElement("http://CIS/BIR/PUBL/2014/07","Zaloguj",__xml);
        __handler.getBody().appendChild(__mainNode);

        org.w3c.dom.Element __pKluczUzytkownikaItemElement=__handler.writeElementWithType(pKluczUzytkownika,String.class, "pKluczUzytkownika", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pKluczUzytkownikaItemElement != null)
        {
            __pKluczUzytkownikaItemElement.setTextContent(pKluczUzytkownika);
        }
        __handler.finishEnvelopeXml(__xml);
        return __xml;
    }
    
    public String Zaloguj(final String pKluczUzytkownika) throws java.lang.Exception
    {
        FMDRequestResultHandler __handler =createRequestResultHandler();
        org.w3c.dom.Document __xml=createZalogujRequest(pKluczUzytkownika, __handler);
        sendRequest("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj",__xml,__handler);
        org.w3c.dom.Node __result=FMDHelper.getResult(__handler.getOutputBody(), "ZalogujResult",false);
        if(__result!=null)
        {
            return __result.getTextContent();
        }
        return null;
    }
    private org.w3c.dom.Document createWylogujRequest(final String pIdentyfikatorSesji,FMDRequestResultHandler __handler) throws java.lang.Exception
    {
        org.w3c.dom.Document __xml=__handler.createEnvelopeXml();
        ArrayList<String> __referenceParameters = new ArrayList<>();
        __handler.addWSAddressingHeaders("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", "http://www.w3.org/2005/08/addressing/anonymous", this.url, __referenceParameters);
        org.w3c.dom.Element __mainNode=__handler.writeElement("http://CIS/BIR/PUBL/2014/07","Wyloguj",__xml);
        __handler.getBody().appendChild(__mainNode);

        org.w3c.dom.Element __pIdentyfikatorSesjiItemElement=__handler.writeElementWithType(pIdentyfikatorSesji,String.class, "pIdentyfikatorSesji", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pIdentyfikatorSesjiItemElement != null)
        {
            __pIdentyfikatorSesjiItemElement.setTextContent(pIdentyfikatorSesji);
        }
        __handler.finishEnvelopeXml(__xml);
        return __xml;
    }
    
    public Boolean Wyloguj(final String pIdentyfikatorSesji) throws java.lang.Exception
    {
        FMDRequestResultHandler __handler =createRequestResultHandler();
        org.w3c.dom.Document __xml=createWylogujRequest(pIdentyfikatorSesji, __handler);
        sendRequest("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj",__xml,__handler);
        org.w3c.dom.Node __result=FMDHelper.getResult(__handler.getOutputBody(), "WylogujResult",false);
        if(__result!=null)
        {
            return FMDHelper.toBoolFromString(__result.getTextContent());
        }
        return null;
    }
    private org.w3c.dom.Document createDaneSzukajPodmiotyRequest(final String pParametryWyszukiwania,FMDRequestResultHandler __handler) throws java.lang.Exception
    {
        org.w3c.dom.Document __xml=__handler.createEnvelopeXml();
        ArrayList<String> __referenceParameters = new ArrayList<>();
        __handler.addWSAddressingHeaders("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajPodmioty", "http://www.w3.org/2005/08/addressing/anonymous", this.url, __referenceParameters);
        org.w3c.dom.Element __mainNode=__handler.writeElement("http://CIS/BIR/PUBL/2014/07","DaneSzukajPodmioty",__xml);
        __handler.getBody().appendChild(__mainNode);

        org.w3c.dom.Element __pParametryWyszukiwaniaItemElement=__handler.writeElementWithType(pParametryWyszukiwania,String.class, "pParametryWyszukiwania", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pParametryWyszukiwaniaItemElement != null)
        {
            __pParametryWyszukiwaniaItemElement.setTextContent(pParametryWyszukiwania);
        }
        __handler.finishEnvelopeXml(__xml);
        return __xml;
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String DaneSzukajPodmioty(final String pParametryWyszukiwania) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    private org.w3c.dom.Document createDanePobierzPelnyRaportRequest(final String pRegon,final String pNazwaRaportu,FMDRequestResultHandler __handler) throws java.lang.Exception
    {
        org.w3c.dom.Document __xml=__handler.createEnvelopeXml();
        ArrayList<String> __referenceParameters = new ArrayList<>();
        __handler.addWSAddressingHeaders("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", "http://www.w3.org/2005/08/addressing/anonymous", this.url, __referenceParameters);
        org.w3c.dom.Element __mainNode=__handler.writeElement("http://CIS/BIR/PUBL/2014/07","DanePobierzPelnyRaport",__xml);
        __handler.getBody().appendChild(__mainNode);

        org.w3c.dom.Element __pRegonItemElement=__handler.writeElementWithType(pRegon,String.class, "pRegon", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pRegonItemElement != null)
        {
            __pRegonItemElement.setTextContent(pRegon);
        }

        org.w3c.dom.Element __pNazwaRaportuItemElement=__handler.writeElementWithType(pNazwaRaportu,String.class, "pNazwaRaportu", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pNazwaRaportuItemElement != null)
        {
            __pNazwaRaportuItemElement.setTextContent(pNazwaRaportu);
        }
        __handler.finishEnvelopeXml(__xml);
        return __xml;
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String DanePobierzPelnyRaport(final String pRegon,final String pNazwaRaportu) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    private org.w3c.dom.Document createDanePobierzRaportZbiorczyRequest(final String pDataRaportu,final String pNazwaRaportu,FMDRequestResultHandler __handler) throws java.lang.Exception
    {
        org.w3c.dom.Document __xml=__handler.createEnvelopeXml();
        ArrayList<String> __referenceParameters = new ArrayList<>();
        __handler.addWSAddressingHeaders("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzRaportZbiorczy", "http://www.w3.org/2005/08/addressing/anonymous", this.url, __referenceParameters);
        org.w3c.dom.Element __mainNode=__handler.writeElement("http://CIS/BIR/PUBL/2014/07","DanePobierzRaportZbiorczy",__xml);
        __handler.getBody().appendChild(__mainNode);

        org.w3c.dom.Element __pDataRaportuItemElement=__handler.writeElementWithType(pDataRaportu,String.class, "pDataRaportu", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pDataRaportuItemElement != null)
        {
            __pDataRaportuItemElement.setTextContent(pDataRaportu);
        }

        org.w3c.dom.Element __pNazwaRaportuItemElement=__handler.writeElementWithType(pNazwaRaportu,String.class, "pNazwaRaportu", "http://CIS/BIR/PUBL/2014/07", __mainNode, true);
        if(__pNazwaRaportuItemElement != null)
        {
            __pNazwaRaportuItemElement.setTextContent(pNazwaRaportu);
        }
        __handler.finishEnvelopeXml(__xml);
        return __xml;
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String DanePobierzRaportZbiorczy(final String pDataRaportu,final String pNazwaRaportu) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    protected void sendRequest(String soapAction,org.w3c.dom.Document soapBody, FMDRequestResultHandler handler) throws java.lang.Exception
    {
        HashMap< String,String> __headers = new HashMap<>();
        __headers.putAll(httpHeaders);
        __headers.put("SOAPAction",soapAction);        
        String __contentType="application/soap+xml";
        __headers.put("content-type",__contentType+";charset=UTF-8");
        if (userName != null)
        {
            String authStr = userName+":"+password;
            String data=Base64.getEncoder().encodeToString(authStr.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            String authValue = "Basic "+data;
            __headers.put("authorization",authValue);
        }
        String __requestBody=FMDHelper.getStringFromDocument(soapBody);
        if(enableLogging)
        {
            System.out.println("requestDump: "+__requestBody);
        }
        FMDResponseData response=connectionProvider.sendRequest(url,__requestBody, __headers,handler, __contentType);
        if(enableLogging)
        {
             System.out.println("responseDump: "+response.getBody());
        }
        handler.setResponse(response);
    }
}
