

package com.example.companyfind.gus;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: A1FD148DE831CDAA5425905FF4FD05D6C2AAC623EEC2913D71D550BDFE0F823C1D7A95A12C8821A6F7359FB4571406AC6C7E3491B4BDEC94D9B4105B9E24C0B0
//------------------------------------------------------------------------

public class FMDSoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public FMDSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public FMDSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}